# -*- coding: utf-8 -*-
"""board.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sopzs7QyOMcmneZ_17J2CZXHXPAmYaUJ
"""

board = []

for row in range(3):
  board.append([])
  for column in range(3):
    board[row].append('-')

def print_board(board):
  for row in board:
    print (" ".join(row))

print_board(board)