# -*- coding: utf-8 -*-
"""board.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sopzs7QyOMcmneZ_17J2CZXHXPAmYaUJ
"""

board = []

for row in range(3):
  board.append([])
  for column in range(3):
    board[row].append('-')

def print_board():
  for row in board:
    print (" ".join(row))

def check_mark(row,col):
  if row > 2 or col > 2 or row < 0 or col < 0:
    return False  

  return board[row][col] != 'x' and board[row][col] != 'o'

def place_mark(row, col, player_id):
  if player_id == 1:
    board[row][col] = 'x'
  else:
    board[row][col] = 'o'

def check_win():
  for rows in range(len(board)):
    if board[rows][0] == 'x' and board[rows][1] == 'x' and board[rows][2] == 'x':
      return 1
    elif board[rows][0] == 'o' and board[rows][1] == 'o' and board[rows][2] == 'o':
      return 2

  for columns in range(len(board)):
    if board[0][columns] == 'x' and board[1][columns] == 'x' and board[2][columns] == 'x':
      return 1
    elif board[0][columns] == 'o' and board[1][columns] == 'o' and board[2][columns] == 'o':
      return 2

  if board[0][0] == 'x' and board[1][1] == 'x' and board[2][2] == 'x':
    return 1
  elif board[0][0] == 'o' and board[1][1] == 'o' and board[1][2] == 'o':
    return 2

  if board[0][2] == 'x' and board[1][1] == 'x' and board[2][0] == 'x':
    return 1
  elif board[0][2] == 'o' and board[1][1] == 'o' and board[2][0] == 'o':
    return 2

  available_moves = 0
  for i in range(len(board)):
    for j in range(len(board)):
      if check_mark(i, j):
        available_moves += 1

  if available_moves == 0:
    return -1
  else:
    return 0

player_id = 1

while True:
  print_board()

  if player_id == 1:
    print('Player 1\'s turn')
  else:
    print('Player 2\'s turn')

  print('Enter row number (0-2)')
  row = int(input())

  print('Enter column number (0-2)')
  col = int(input())

  if not check_mark(row, col):
    print('Please enter a row and column that hasn\'t been taken')
    continue

  place_mark(row, col, player_id)

  winner = check_win()

  if winner == 1:
    print('Player 1 wins!')
    print_board()
    break
  elif winner == 2:
    print('Player 2 wins!')
    print_board()
    break
  elif winner == -1:
    print('Stalemate')
    print_board()
    break

  if player_id == 1:
    player_id = 2
  else:
    player_id = 1